### ISSUE TITLE
Crash on latest 1.1.4

### ISSUE THREAD

**Issue by SHXRKIEgg** [Senior-S/JustLeveling-Fork#12] opened 2024-09-25 11:01 UTC
Seems to be some issue between JustLeveling and Better Combat
https://mclo.gs/uymmOV8

**Comment by Senior-S** [comment] 2024-09-25 23:32
Fixed on version 1.1.5, it was caused by an new feature, sorry for the issue.

https://github.com/Senior-S/JustLeveling-Fork/releases/tag/1.1.5

**Closed by Senior-S** 2024-09-25 23:32 UTC
